### ISSUE TITLE
Bug: Wrong Network Notice 

### ISSUE THREAD

**Issue by jonathanstanley** [aragon/app-legacy#1249]
**Describe the bug**
cannot create dao due to "Wrong Network" error

**To Reproduce (please complete the following information)**

1. web3 sign-in using trust wallet / wallet connect (with support for ethereum, arbitrum, and polygon).
2. configure dao to use arbitrum chain
3. click create dao
4. receive [chain network error](https://github.com/aragon/app/blob/e8b6a4654e2ed3891a15bc7dc5c2654a22c5e4ea/src/context/update.tsx#L318) `Wrong network. The action can't be executed because you are in the wrong network. Change to the Arbitrum on your wallet and try again.`

**Current behavior**
throws error. dao creation is blocked for arbitrum

**Expected behavior**
should not throw error

**System (please complete the following information):**
 - Brave Browser (also attempted with Brave Shield disabled)
 - Trust Wallet - wallet connect sign-in authorization allows arbitrum transactions

**Additional context**
* There is a similar issue with a different dapp: https://support.allianceblock.io/support/solutions/articles/80000600434-i-receive-a-wrong-network-message-when-using-trust-wallet
* I see [other dapps show a network switch tool](https://github.com/Uniswap/interface/issues/3617), however the network is already selected as part of the dao creation process.

**Comment by jonathanstanley** [comment]
I think this may be related:
https://github.com/aragon/app/blob/e8b6a4654e2ed3891a15bc7dc5c2654a22c5e4ea/src/hooks/useWallet.tsx#L52-L56

aragon is using wagmi `useNetwork` however wagmi has removed that tool:
https://wagmi.sh/react/guides/migrate-from-v1-to-v2#removed-usenetwork-hook

and perhaps use the plural `const { chains } = useConfig()`

**Comment by jasonttian** [comment]
I would like to fix this isssue.
Let me know if you are interested.
Thx.

**Comment by Barukimang** [comment]
Just seeing this now @jonathanstanley, good to know about this. One of our Devs is working on updating Wagmi, will check whether this issue has resolved by next week.

In some apps you cannot select the network anymore (like Rainbow) and depend on the network switch tool you mention. Not sure for Trust though, but adding this tool is on our timeline as well.

Thanks for the feedback!

**Comment by Barukimang** [comment]
Hi guys! We have updated the WAGMI package. Could you check whether wallet connections are working well for you now?

**Comment by jonathanstanley** [comment]
Thanks. FWIW, I still get the same error as I described earlier
<img width="1313" alt="Screenshot 2024-04-17 at 10 37 04 PM" src="https://github.com/aragon/app/assets/2755958/14851aeb-0876-44c1-ba4a-3755f424c077">

**Comment by Barukimang** [comment]
Gm @jonathanstanley Seems like some other wallet connect issues have been fixed, but not yet this one where we need to implement a network switcher in our App for wallets that now depend on it. It's on our TD list though.
